/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type CustomerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "customer";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: number;
  item?: Array<{
    product?: ProductReference;
    quantity?: number;
    priceAtPurchase?: number;
    _key: string;
  }>;
  totalCost?: number;
  customer?: CustomerReference;
  clerkUserId?: string;
  email?: string;
  PhoneNumber?: number;
  address?: {
    name?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    country?: string;
  };
  stripeCustomerId?: string;
  createdAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type SubcategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "subcategory";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  description?: string;
  price?: number;
  discount?: number;
  category?: CategoryReference;
  subcategory?: SubcategoryReference;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  stock?: number;
  color?:
    | "multicolor"
    | "black"
    | "white"
    | "red"
    | "pink"
    | "hot-pink"
    | "rose"
    | "nude"
    | "peach"
    | "coral"
    | "orange"
    | "yellow"
    | "gold"
    | "silver"
    | "bronze"
    | "brown"
    | "beige"
    | "tan"
    | "ivory"
    | "champagne"
    | "purple"
    | "lavender"
    | "violet"
    | "blue"
    | "navy"
    | "teal"
    | "green"
    | "olive"
    | "mint"
    | "gray"
    | "charcoal"
    | "burgundy"
    | "maroon"
    | "wine";
  productForm?:
    | "liquid"
    | "cream"
    | "gel"
    | "oil"
    | "solid"
    | "semi-solid"
    | "powder"
    | "stick"
    | "balm"
    | "wax"
    | "mousse"
    | "foam"
    | "mist"
    | "spray"
    | "serum"
    | "lotion"
    | "butter"
    | "paste"
    | "clay"
    | "crayon"
    | "pencil"
    | "roll-on"
    | "pressed-powder"
    | "loose-powder";
  dimension?: string;
  featured?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Customer = {
  _id: string;
  _type: "customer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  clerkUserId?: string;
  stripeCustomerId?: string;
  createdAt?: string;
};

export type Subcategory = {
  _id: string;
  _type: "subcategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  category?: CategoryReference;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  author?: AuthorReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | CustomerReference
  | Order
  | CategoryReference
  | SubcategoryReference
  | SanityImageAssetReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Customer
  | Subcategory
  | AuthorReference
  | Post
  | BlockContent
  | Author
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/queries/categories.ts
// Variable: ALL_CATEGORIES_QUERY
// Query: *[_type == 'category'] | order(title asc) {    _id,    title,    "slug": slug.current,    description,    "image": image{      asset->{        _id,        url      },      hotspot    }  }
export type ALL_CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
}>;

// Source: sanity/queries/categories.ts
// Variable: CATEGORY_BY_SLUG_QUERY
// Query: *[    _type == "category" &&    slug.current == $slug  ][0] {    _id,    title,    "slug": slug.current,    description,    "image": image {      asset-> {        _id,        url      },      hotspot    },    "subcategories": *[      _type == "subcategory" &&      category._ref == ^._id    ] | order(title asc) {      _id,      title,      "slug": slug.current,      description,      "image": image {        asset-> {          _id,          url        },        hotspot      }    }  }
export type CATEGORY_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  description: string | null;
  image: {
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  subcategories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
    description: string | null;
    image: {
      asset: {
        _id: string;
        url: string | null;
      } | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  }>;
} | null;

// Source: sanity/queries/categories.ts
// Variable: CATEGORY_WITH_PRODUCTS_QUERY
// Query: *[    _type == "category" &&    slug.current == $category  ][0] {    _id,    title,    description,    "slug": slug.current,    "subcategories": *[      _type == "subcategory" &&      category._ref == ^._id    ] | order(title asc) {      _id,      title,      "slug": slug.current    },    "products": *[      _type == "product" &&      category._ref in ^.subcategories[]._id    ] | order(_createdAt desc) {      _id,      name,      "slug": slug.current,      description,      price,      discount,      stock,      color,      dimension,      featured,      "image": images[0]{        asset->{          _id,          url        }      }    }  }
export type CATEGORY_WITH_PRODUCTS_QUERY_RESULT = {
  _id: string;
  title: string | null;
  description: string | null;
  slug: string | null;
  subcategories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }>;
  products: Array<never>;
} | null;

// Source: sanity/queries/customer.ts
// Variable: CUSTOMER_BY_EMAIL_QUERY
// Query: * [  _type == "customer" && email == $email ] [0]     {        _id,        name,        email,    }
export type CUSTOMER_BY_EMAIL_QUERY_RESULT = {
  _id: string;
  name: string | null;
  email: string | null;
} | null;

// Source: sanity/queries/orders.ts
// Variable: ALL_ORDERS_QUERY
// Query: *[_type == "order"] {    _id,    orderNumber,    totalCost,    email,    PhoneNumber,  }
export type ALL_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: number | null;
  totalCost: number | null;
  email: string | null;
  PhoneNumber: number | null;
}>;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_USER_QUERY
// Query: *[ _type == "order" && clerkUserId == $clerkUserId] | order(createdAt desc)  {    _id,    orderNumber,    totalCost,    createdAt,    email,    PhoneNumber,    clerkUserId,    "itemCount": count(item),    "itemNames": item[].product->name,  }
export type ORDER_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: number | null;
  totalCost: number | null;
  createdAt: string | null;
  email: string | null;
  PhoneNumber: number | null;
  clerkUserId: string | null;
  itemCount: number | null;
  itemNames: Array<string | null> | null;
}>;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_ID_QUERY
// Query: *[ _type == " order" && _id == $_id] [0]   {     _id,    orderNumber,    clerkUserId,    email,    item[]    {        _key,        quantity,        priceAtPurchase,        product->        {              _id,              name,              "slug": slug.current,              "image": images[0]              {                      asset->                      {                        _id,                        url                      }              }        }    },    totalCost,    address    {        name,        line1,        line2,        city,        postcode,        country,    },    stripeCustomerId,     createdAt,  }
export type ORDER_BY_ID_QUERY_RESULT = null;

// Source: sanity/queries/orders.ts
// Variable: RECENT_ORDERS_QUERY
// Query: *[ _type == "order"] | order(createdAt desc){       _id,    orderNumber,      email,    totalCost,   createdAt,  }
export type RECENT_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: number | null;
  email: string | null;
  totalCost: number | null;
  createdAt: string | null;
}>;

// Source: sanity/queries/orders.ts
// Variable: ORDER_BY_STRIPE_PAYMENT_ID_QUERY
// Query: *[ _type == "order" && stripeCustomerId == $stripeCustomerId ] [0]{ _id }
export type ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT = {
  _id: string;
} | null;

// Source: sanity/queries/product.ts
// Variable: PRODUCTS_BY_SUBCATEGORY_QUERY
// Query: *[    _type == "product"    && subcategory->slug.current == $subcategorySlug  ]  | order(name asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type PRODUCTS_BY_SUBCATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: ALL_PRODUCTS_QUERY
// Query: *[    _type == "product"  ]  | order(name asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type ALL_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[    _type == "product"    && featured == true    && stock > 0  ]  | order(name asc)[0...6]  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: PRODUCTS_BY_CATEGORY_QUERY
// Query: *[    _type == "product"    && category->slug.current == $categorySlug  ]  | order(name asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type PRODUCTS_BY_CATEGORY_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[    _type == "product"    && slug.current == $slug  ][0]  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
} | null;

// Source: sanity/queries/product.ts
// Variable: PRODUCT_BY_ID_QUERY
// Query: *[    _type == "product"    && _id == $productId  ][0]  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type PRODUCT_BY_ID_QUERY_RESULT = {
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
} | null;

// Source: sanity/queries/product.ts
// Variable: FILTER_PRODUCTS_BY_NAME_QUERY
// Query: *[      _type == "product"  && (    $categorySlug == ""    || category->slug.current == $categorySlug  )  && (    $color == ""    || color == $color  )  && (    $productForm == ""    || productForm == $productForm  )  && (    $minPrice == 0    || price >= $minPrice  )  && (    $maxPrice == 0    || price <= $maxPrice  )  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"  )  && (    $inStock == false    || stock > 0  )  ]  | order(name asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type FILTER_PRODUCTS_BY_NAME_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_ASC_QUERY
// Query: *[      _type == "product"  && (    $categorySlug == ""    || category->slug.current == $categorySlug  )  && (    $color == ""    || color == $color  )  && (    $productForm == ""    || productForm == $productForm  )  && (    $minPrice == 0    || price >= $minPrice  )  && (    $maxPrice == 0    || price <= $maxPrice  )  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"  )  && (    $inStock == false    || stock > 0  )  ]  | order(price asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: FILTER_PRODUCTS_BY_PRICE_DESC_QUERY
// Query: *[      _type == "product"  && (    $categorySlug == ""    || category->slug.current == $categorySlug  )  && (    $color == ""    || color == $color  )  && (    $productForm == ""    || productForm == $productForm  )  && (    $minPrice == 0    || price >= $minPrice  )  && (    $maxPrice == 0    || price <= $maxPrice  )  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"  )  && (    $inStock == false    || stock > 0  )  ]  | order(price desc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: FILTER_PRODUCTS_BY_RELEVANCE_QUERY
// Query: *[      _type == "product"  && (    $categorySlug == ""    || category->slug.current == $categorySlug  )  && (    $color == ""    || color == $color  )  && (    $productForm == ""    || productForm == $productForm  )  && (    $minPrice == 0    || price >= $minPrice  )  && (    $maxPrice == 0    || price <= $maxPrice  )  && (    $searchQuery == ""    || name match $searchQuery + "*"    || description match $searchQuery + "*"  )  && (    $inStock == false    || stock > 0  )  ]  | score(      boost(name match $searchQuery + "*", 3),      boost(description match $searchQuery + "*", 1)    )  | order(_score desc, name asc)  {  _id,  name,  "slug": slug.current,  description,  price,  discount,  "images": images[0...8]{    _key,    asset->{      _id,      url    },    hotspot,    crop  },  category->{    _id,    title,    "slug": slug.current  },  stock,  color,  productForm,  dimension,  featured}
export type FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: SEARCH_PRODUCTS_QUERY
// Query: *[    _type == "product"    && (      name match $searchQuery + "*"      || description match $searchQuery + "*"    )  ]  | score(      boost(name match $searchQuery + "*", 3),      boost(description match $searchQuery + "*", 1)    )  | order(_score desc, name asc)  {    _id,    _score,    name,    "slug": slug.current,    description,    price,    discount,    "images": images[0...8]{      _key,      asset->{        _id,        url      },      hotspot,      crop    },    category->{      _id,      title,      "slug": slug.current    },    stock,    color,    productForm,    dimension,    featured  }
export type SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  _score: null;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Source: sanity/queries/product.ts
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[    _type == "product"    && _id in $ids  ]{    _id,    name,    "slug": slug.current,    price,    discount,    "images": images[0...4]{      _key,      asset->{        _id,        url      },      hotspot,      crop    },    stock  }
export type PRODUCTS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  stock: number | null;
}>;

// Source: sanity/queries/product.ts
// Variable: LOW_STOCK_PRODUCTS_QUERY
// Query: *[    _type == "product"    && stock > 0    && stock <= 5  ]  | order(stock asc)  {    _id,    name,    "slug": slug.current,    stock,    "image": images[0]{      _key,      asset->{        _id,        url      },      hotspot,      crop    }  }
export type LOW_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  stock: number | null;
  image: {
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/queries/product.ts
// Variable: OUT_OF_STOCK_PRODUCTS_QUERY
// Query: *[    _type == "product"    && stock == 0  ]  | order(name asc)  {    _id,    name,    "slug": slug.current,    "image": images[0]{      _key,      asset->{        _id,        url      },      hotspot,      crop    }  }
export type OUT_OF_STOCK_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  image: {
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
}>;

// Source: sanity/queries/product.ts
// Variable: AI_SEARCH_PRODUCTS_QUERY
// Query: *[    _type == "product"    && (      $searchQuery == ""      || name match $searchQuery + "*"      || description match $searchQuery + "*"      || category->title match $searchQuery + "*"    )    && (      $categorySlug == ""      || category->slug.current == $categorySlug    )    && (      $color == ""      || color == $color    )    && (      $productForm == ""      || productForm == $productForm    )    && (      $minPrice == 0      || price >= $minPrice    )    && (      $maxPrice == 0      || price <= $maxPrice    )  ]  | order(name asc)[0...20]  {    _id,    name,    "slug": slug.current,    description,    price,    discount,    "images": images[0...4]{      _key,      asset->{        _id,        url      },      hotspot,      crop    },    category->{      _id,      title,      "slug": slug.current    },    stock,    color,    productForm,    dimension,    featured  }
export type AI_SEARCH_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  description: string | null;
  price: number | null;
  discount: number | null;
  images: Array<{
    _key: string;
    asset: {
      _id: string;
      url: string | null;
    } | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  }> | null;
  category: {
    _id: string;
    title: string | null;
    slug: string | null;
  } | null;
  stock: number | null;
  color:
    | "beige"
    | "black"
    | "blue"
    | "bronze"
    | "brown"
    | "burgundy"
    | "champagne"
    | "charcoal"
    | "coral"
    | "gold"
    | "gray"
    | "green"
    | "hot-pink"
    | "ivory"
    | "lavender"
    | "maroon"
    | "mint"
    | "multicolor"
    | "navy"
    | "nude"
    | "olive"
    | "orange"
    | "peach"
    | "pink"
    | "purple"
    | "red"
    | "rose"
    | "silver"
    | "tan"
    | "teal"
    | "violet"
    | "white"
    | "wine"
    | "yellow"
    | null;
  productForm:
    | "balm"
    | "butter"
    | "clay"
    | "crayon"
    | "cream"
    | "foam"
    | "gel"
    | "liquid"
    | "loose-powder"
    | "lotion"
    | "mist"
    | "mousse"
    | "oil"
    | "paste"
    | "pencil"
    | "powder"
    | "pressed-powder"
    | "roll-on"
    | "semi-solid"
    | "serum"
    | "solid"
    | "spray"
    | "stick"
    | "wax"
    | null;
  dimension: string | null;
  featured: boolean | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == \'category\'] | order(title asc) {\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n    "image": image{\n      asset->{\n        _id,\n        url\n      },\n      hotspot\n    }\n  }': ALL_CATEGORIES_QUERY_RESULT;
    '\n  *[\n    _type == "category" &&\n    slug.current == $slug\n  ][0] {\n\n    _id,\n    title,\n    "slug": slug.current,\n    description,\n\n    "image": image {\n      asset-> {\n        _id,\n        url\n      },\n      hotspot\n    },\n\n    "subcategories": *[\n      _type == "subcategory" &&\n      category._ref == ^._id\n    ] | order(title asc) {\n\n      _id,\n      title,\n      "slug": slug.current,\n      description,\n\n      "image": image {\n        asset-> {\n          _id,\n          url\n        },\n        hotspot\n      }\n    }\n  }\n': CATEGORY_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type == "category" &&\n    slug.current == $category\n  ][0] {\n\n    _id,\n    title,\n    description,\n    "slug": slug.current,\n\n    "subcategories": *[\n      _type == "subcategory" &&\n      category._ref == ^._id\n    ] | order(title asc) {\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    "products": *[\n      _type == "product" &&\n      category._ref in ^.subcategories[]._id\n    ] | order(_createdAt desc) {\n      _id,\n      name,\n      "slug": slug.current,\n      description,\n      price,\n      discount,\n      stock,\n      color,\n      dimension,\n      featured,\n\n      "image": images[0]{\n        asset->{\n          _id,\n          url\n        }\n      }\n    }\n  }\n': CATEGORY_WITH_PRODUCTS_QUERY_RESULT;
    '* [  _type == "customer" && email == $email ] [0] \n    {\n        _id,\n        name,\n        email,\n\n    }\n': CUSTOMER_BY_EMAIL_QUERY_RESULT;
    '\n  *[_type == "order"] {\n\n    _id,\n    orderNumber,\n    totalCost,\n    email,\n    PhoneNumber,\n  } \n': ALL_ORDERS_QUERY_RESULT;
    '\n  *[ _type == "order" && clerkUserId == $clerkUserId] | order(createdAt desc)\n  {\n    _id,\n    orderNumber,\n    totalCost,\n    createdAt,\n    email,\n    PhoneNumber,\n    clerkUserId,\n    "itemCount": count(item),\n    "itemNames": item[].product->name,\n\n  }': ORDER_BY_USER_QUERY_RESULT;
    ' \n  *[ _type == " order" && _id == $_id] [0] \n  {\n     _id,\n    orderNumber,\n    clerkUserId,\n    email,\n    item[]\n    {\n        _key,\n        quantity,\n        priceAtPurchase,\n        product->\n        {\n              _id,\n              name,\n              "slug": slug.current,\n              "image": images[0]\n              {\n                      asset->\n                      {\n                        _id,\n                        url\n                      }\n              }\n        }\n    },\n    totalCost,\n    address\n    {\n        name,\n        line1,\n        line2,\n        city,\n        postcode,\n        country,\n    },\n    stripeCustomerId,\n     createdAt,\n  } ': ORDER_BY_ID_QUERY_RESULT;
    ' \n   *[ _type == "order"] | order(createdAt desc){\n       _id,\n    orderNumber,  \n    email,\n    totalCost,\n   createdAt,\n  }\n  ': RECENT_ORDERS_QUERY_RESULT;
    '\n  *[ _type == "order" && stripeCustomerId == $stripeCustomerId ] [0]{ _id } ': ORDER_BY_STRIPE_PAYMENT_ID_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && subcategory->slug.current == $subcategorySlug\n  ]\n  | order(name asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': PRODUCTS_BY_SUBCATEGORY_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n  ]\n  | order(name asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': ALL_PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && featured == true\n    && stock > 0\n  ]\n  | order(name asc)[0...6]\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': FEATURED_PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && category->slug.current == $categorySlug\n  ]\n  | order(name asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': PRODUCTS_BY_CATEGORY_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && slug.current == $slug\n  ][0]\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': PRODUCT_BY_SLUG_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && _id == $productId\n  ][0]\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': PRODUCT_BY_ID_QUERY_RESULT;
    '\n  *[\n    \n  _type == "product"\n\n  && (\n    $categorySlug == ""\n    || category->slug.current == $categorySlug\n  )\n\n  && (\n    $color == ""\n    || color == $color\n  )\n\n  && (\n    $productForm == ""\n    || productForm == $productForm\n  )\n\n  && (\n    $minPrice == 0\n    || price >= $minPrice\n  )\n\n  && (\n    $maxPrice == 0\n    || price <= $maxPrice\n  )\n\n  && (\n    $searchQuery == ""\n    || name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n  )\n\n  && (\n    $inStock == false\n    || stock > 0\n  )\n\n  ]\n  | order(name asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': FILTER_PRODUCTS_BY_NAME_QUERY_RESULT;
    '\n  *[\n    \n  _type == "product"\n\n  && (\n    $categorySlug == ""\n    || category->slug.current == $categorySlug\n  )\n\n  && (\n    $color == ""\n    || color == $color\n  )\n\n  && (\n    $productForm == ""\n    || productForm == $productForm\n  )\n\n  && (\n    $minPrice == 0\n    || price >= $minPrice\n  )\n\n  && (\n    $maxPrice == 0\n    || price <= $maxPrice\n  )\n\n  && (\n    $searchQuery == ""\n    || name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n  )\n\n  && (\n    $inStock == false\n    || stock > 0\n  )\n\n  ]\n  | order(price asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': FILTER_PRODUCTS_BY_PRICE_ASC_QUERY_RESULT;
    '\n  *[\n    \n  _type == "product"\n\n  && (\n    $categorySlug == ""\n    || category->slug.current == $categorySlug\n  )\n\n  && (\n    $color == ""\n    || color == $color\n  )\n\n  && (\n    $productForm == ""\n    || productForm == $productForm\n  )\n\n  && (\n    $minPrice == 0\n    || price >= $minPrice\n  )\n\n  && (\n    $maxPrice == 0\n    || price <= $maxPrice\n  )\n\n  && (\n    $searchQuery == ""\n    || name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n  )\n\n  && (\n    $inStock == false\n    || stock > 0\n  )\n\n  ]\n  | order(price desc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': FILTER_PRODUCTS_BY_PRICE_DESC_QUERY_RESULT;
    '\n  *[\n    \n  _type == "product"\n\n  && (\n    $categorySlug == ""\n    || category->slug.current == $categorySlug\n  )\n\n  && (\n    $color == ""\n    || color == $color\n  )\n\n  && (\n    $productForm == ""\n    || productForm == $productForm\n  )\n\n  && (\n    $minPrice == 0\n    || price >= $minPrice\n  )\n\n  && (\n    $maxPrice == 0\n    || price <= $maxPrice\n  )\n\n  && (\n    $searchQuery == ""\n    || name match $searchQuery + "*"\n    || description match $searchQuery + "*"\n  )\n\n  && (\n    $inStock == false\n    || stock > 0\n  )\n\n  ]\n  | score(\n      boost(name match $searchQuery + "*", 3),\n      boost(description match $searchQuery + "*", 1)\n    )\n  | order(_score desc, name asc)\n  {\n  _id,\n  name,\n  "slug": slug.current,\n  description,\n  price,\n  discount,\n\n  "images": images[0...8]{\n    _key,\n    asset->{\n      _id,\n      url\n    },\n    hotspot,\n    crop\n  },\n\n  category->{\n    _id,\n    title,\n    "slug": slug.current\n  },\n\n  stock,\n  color,\n  productForm,\n  dimension,\n  featured\n}\n': FILTER_PRODUCTS_BY_RELEVANCE_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && (\n      name match $searchQuery + "*"\n      || description match $searchQuery + "*"\n    )\n  ]\n  | score(\n      boost(name match $searchQuery + "*", 3),\n      boost(description match $searchQuery + "*", 1)\n    )\n  | order(_score desc, name asc)\n  {\n    _id,\n    _score,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    discount,\n\n    "images": images[0...8]{\n      _key,\n      asset->{\n        _id,\n        url\n      },\n      hotspot,\n      crop\n    },\n\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    stock,\n    color,\n    productForm,\n    dimension,\n    featured\n  }\n': SEARCH_PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && _id in $ids\n  ]{\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    discount,\n\n    "images": images[0...4]{\n      _key,\n      asset->{\n        _id,\n        url\n      },\n      hotspot,\n      crop\n    },\n\n    stock\n  }\n': PRODUCTS_BY_IDS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && stock > 0\n    && stock <= 5\n  ]\n  | order(stock asc)\n  {\n    _id,\n    name,\n    "slug": slug.current,\n    stock,\n\n    "image": images[0]{\n      _key,\n      asset->{\n        _id,\n        url\n      },\n      hotspot,\n      crop\n    }\n  }\n': LOW_STOCK_PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n    && stock == 0\n  ]\n  | order(name asc)\n  {\n    _id,\n    name,\n    "slug": slug.current,\n\n    "image": images[0]{\n      _key,\n      asset->{\n        _id,\n        url\n      },\n      hotspot,\n      crop\n    }\n  }\n': OUT_OF_STOCK_PRODUCTS_QUERY_RESULT;
    '\n  *[\n    _type == "product"\n\n    && (\n      $searchQuery == ""\n      || name match $searchQuery + "*"\n      || description match $searchQuery + "*"\n      || category->title match $searchQuery + "*"\n    )\n\n    && (\n      $categorySlug == ""\n      || category->slug.current == $categorySlug\n    )\n\n    && (\n      $color == ""\n      || color == $color\n    )\n\n    && (\n      $productForm == ""\n      || productForm == $productForm\n    )\n\n    && (\n      $minPrice == 0\n      || price >= $minPrice\n    )\n\n    && (\n      $maxPrice == 0\n      || price <= $maxPrice\n    )\n  ]\n  | order(name asc)[0...20]\n  {\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    discount,\n\n    "images": images[0...4]{\n      _key,\n      asset->{\n        _id,\n        url\n      },\n      hotspot,\n      crop\n    },\n\n    category->{\n      _id,\n      title,\n      "slug": slug.current\n    },\n\n    stock,\n    color,\n    productForm,\n    dimension,\n    featured\n  }\n': AI_SEARCH_PRODUCTS_QUERY_RESULT;
  }
}
