import type { Metadata } from "next";
import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from '@clerk/nextjs'

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Link from 'next/link' // Added for navigation


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        <body className="bg-black text-white">
          
          {/* NAVIGATION BAR */}
          <header className="flex justify-between items-center p-4 h-16 border-b">
            
            {/* 1. Left Side: Logo */}
            <Link href="/" className="flex items-center gap-2 font-bold text-xl">
                <span className="hidden sm:block">MakeUp</span>
                 <div className="w-12 h-8  bg-white text-black rounded-md flex items-center justify-center text-xs"> WALA </div>
            </Link>

            {/* 2. Middle: Navigation Links */}
            <nav className="hidden md:flex gap-8 font-medium text-[#27E884]">
              <Link href="/" className="hover:text-[#975499] transition-colors">Home</Link>
              <Link href="/about" className="hover:text-[#975499] transition-colors">About</Link>
              <Link href="/contact" className="hover:text-[#975499] transition-colors">Contact</Link>
              <Link href="/products" className="hover:text-[#975499] transition-colors">Products</Link>
              <Link href="/appointment" className="hover:text-[#975499] transition-colors">Services</Link>
            </nav>

            {/* 3. Right Side: Auth Buttons */}
            <div className="flex items-center gap-4">
              <Show when="signed-out">
                <SignInButton>
                  <button className="bg-[#E4D5E1]  hover:bg-[#0241BE] hover:text-white text-black rounded-full font-medium text-sm sm:text-base h-10 sm:h-10 px-4 sm:px-5 cursor-pointer transition-colors">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#0241BE] hover:bg-[#E4D5E1] text-white  hover:text-black rounded-full font-medium text-sm sm:text-base h-10 sm:h-10 px-4 sm:px-5 cursor-pointer transition-colors">
                    Sign Up
                  </button>
                </SignUpButton>
              </Show>
             
              <Show when="signed-in">
                {/* adding dashboard link */}
             
                <UserButton />
              </Show>
            </div>
            
          </header>

          {/* PAGE CONTENT */}
          <main className="flex-1">
            {children}
          </main>
          
        </body>
      </html>
    </ClerkProvider>
  
  );
}
